#ifndef DBO_RANDOM_H
#define DBO_RANDOM_H
#include <iostream>
#include <stdint.h>
/**
 * The random generator used for the old DBO client encryption seems to be the
 * one by Andrew Kirmse.
 * Class name is renamed to match the same naming convention.
 */

/* Copyright (C) Andrew Kirmse, 2000.  
 * All rights reserved worldwide. 
 * 
 * This software is provided "as is" without express or implied 
 * warranties. You may freely copy and compile this source into 
 * applications you distribute provided that the copyright text 
 * below is included in the resulting source code, for example: 
 * "Portions Copyright (C) Andrew Kirmse, 2000" 
 */  

class dbo_random
{
public:
   dbo_random();
   dbo_random(uint32_t seed);
   ~dbo_random();

   // Generates a full 32 bit random number.
   uint32_t Generate();

   // Generates a positive 32 bit random number.
   int32_t GeneratePositive() { return Generate() & 0x7fffffff; }

protected:
   enum { TABLE_SIZE = 250, };

   // This single seed is used to initialize a simple generator that provides
   // the seeds to the real generator.
   uint32_t state;

   int32_t index1, index2;
   uint32_t table[TABLE_SIZE];

   void GenerateSeeds();

   // Return a new number generated by a simple generator that depends only on state.
   uint32_t GenerateSimple();
};
  

#endif
